### ISSUE TITLE
Commit message configuration.

### ISSUE THREAD

**Issue by vivekimsit** [phuu/commit-lint#2]
I am curious on why can't we use `json` for lint configuration? is their added benefit of using `js`?

**Comment by passy** [comment]
I like the example Tom has provided in the README. The benefit of JS here is that you can use compose your configuration of other modules. If someone has a great regexp or wants to plug in the Angular commit style, they can just import a module for that, but still mix and match with their own custom components.

**Comment by vivekimsit** [comment]
@passy that seems good and reasonable to me.
